// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://nlxlpxddixvieiwsxdbu.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5seGxweGRkaXh2aWVpd3N4ZGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI1NDM4OTQsImV4cCI6MjA0ODExOTg5NH0.jdF4WFDK7wdFLPo3L-OdxrJe8OhRmVLiTbBIhtX2HkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);